# Generated by Django 5.1.4 on 2025-01-10 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('bse_code', models.CharField(max_length=10)),
                ('nse_code', models.CharField(max_length=10)),
                ('website', models.URLField()),
                ('logo_url', models.URLField()),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roce', models.DecimalField(decimal_places=2, max_digits=5)),
                ('roe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('opm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProsAndCons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.company')),
            ],
        ),
    ]
